name: Indigemetrics
favicon: null
layout_spectrum: 0.06161396065726876
typography_spectrum: 0.7830457631498575
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.14300804259255528
  lightness: 0.6022780754137784
  saturation: 0.8665540472138673
  rhythmicContrast: 0.0014473253395408392
purpose: []
